// Generated by CoffeeScript 1.9.2
(function() {
  var Building, Level, LevelCollection;

  Level = (function() {
    function Level(color) {
      var geo, mat;
      this.color = color;
      geo = THREE.BoxGeometry(0.75, 0.75, 1);
      mat = THREE.Material.MeshPhongMaterial({
        color: this.color
      });
      this.model = THREE.Mesh(geo, mat);
    }

    return Level;

  })();

  LevelCollection = (function() {
    function LevelCollection(x, y, levels) {
      this.x = x;
      this.y = y;
      this.levels = levels;
    }

    return LevelCollection;

  })();

  Building = (function() {
    function Building(cells) {
      this.cells = cells;
    }

    Building.prototype.getModel = function() {};

    return Building;

  })();

}).call(this);

//# sourceMappingURL=buildings.js.map
